<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2012-03-06 01:29

$extensionPath = \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('vcardmail');
return array(
	'tx_vcardmail' => $extensionPath . 'class.tx_vcardmail.php',
	'tx_vcardmail_vcard' => $extensionPath . 'libraries/zendvcard/class.tx_vcardmail_vcard.php',
	'tx_vcardmail_vcard_generator' => $extensionPath . 'libraries/zendvcard/Vcard/class.tx_vcardmail_vcard_generator.php',
);
?>
